upload_max_filesize = 100M
post_max_size = 100M
memory_limit = 12288M
;xdebug.mode = coverage
allow_url_fopen = 1

zend_extension = opcache.so
opcache.enable = 1
opcache.enable_cli = 1
opcache.jit_buffer_size = 0
opcache.jit = 0
